language: php

addons:
  chrome: stable
  apt:
    packages:
      - nginx

sudo: false

php: 7.2

env: WP_VERSION=latest WP_MULTISITE=0 RUN_E2E=1 

before_script:
  - git clone --depth=50 --branch=master https://github.com/woocommerce/woocommerce.git woocommerce

script:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - export NODE_CONFIG='{"users":{"admin":{"username":"admin","password":"password"},"customer":{"username":"customer","password":"password"}}}'
  - woocommerce/tests/bin/install.sh woocommerce_test root '' localhost $WP_VERSION
  - woocommerce/tests/bin/run-e2e-CI.sh

branches:
  only:
    - master